apiVersion: v1
kind: Service
metadata:
  name: {{ include "aigc.fullname" . }}
  labels:
    {{- include "aigc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "aigc.selectorLabels" . | nindent 4 }}
