apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "lookout.fullname" . }}-cronjob
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 100
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{- include "lookout.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: Always
              securityContext:
                readOnlyRootFilesystem: true
                runAsUser: 1000
                runAsGroup: 2000
                runAsNonRoot: true
              env:
                - name: LOG_LEVEL
                  value: "info"
                - name: RUN_MODE
                  value: "task"
              {{- if .Values.resources }}
              resources:{{- toYaml .Values.resources | nindent 16 }}
              {{- else if ne .Values.resourcesPreset "none"}}
              resources:{{- include "opspilot.resources.preset" (dict "type" .Values.resourcesPreset) | nindent 16 }}
              {{- end }}
              volumeMounts:
                - mountPath: /opt/configs/config.yaml
                  name: config-volume
                  subPath: config.yaml
          volumes:
            - name: config-volume
              configMap:
                  name: lookout-config
          restartPolicy: OnFailure
          activeDeadlineSeconds: 300