apiVersion: v1
kind: Service
metadata:
  name: {{ include "lookout.fullname" . }}-service
  labels:
    {{- include "lookout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "lookout.selectorLabels" . | nindent 4 }}
